export const TRAINERS = [
  {
    id: "1",
    name: "Marcus Chen",
    slug: "marcus-chen",
    specialty: "Strength & Conditioning",
    experience: 12,
    bio: "Former competitive powerlifter with a passion for helping others unlock their strength potential. Marcus believes in progressive overload and proper form above all else.",
    longBio:
      "Marcus discovered his love for strength training during college, where he competed as a powerlifter at the national level. After earning his NSCA-CSCS certification, he transitioned from competitive lifting to coaching, spending 5 years training athletes before joining Big Vision. His methodology focuses on building a foundation of proper movement patterns, then progressively challenging his clients to reach new personal records. Outside the gym, Marcus is an avid rock climber and nutrition enthusiast.",
    certifications: ["NSCA-CSCS", "USAW Level 2", "Precision Nutrition L1"],
    specialties: ["Powerlifting", "Bodybuilding", "Athletic Performance"],
    image: "/images/trainers/trainer-1.jpg",
    instagram: "@marcuslifts",
    classTypes: ["Strength"],
  },
  {
    id: "2",
    name: "Sarah Williams",
    slug: "sarah-williams",
    specialty: "HIIT & Functional Training",
    experience: 8,
    bio: "High-energy coach who specializes in transformative group fitness experiences. Sarah's classes are legendary for their intensity and fun factor.",
    longBio:
      "Sarah's fitness journey started as a way to manage stress in her corporate career. She fell so in love with training that she left the corporate world to become a full-time fitness professional. With CrossFit L2 and ACE-CPT certifications, she combines functional movement with high-intensity protocols to deliver classes that are both challenging and addictive. Her energy is infectious, and she has a gift for pushing people past their perceived limits while keeping the atmosphere fun and supportive.",
    certifications: ["ACE-CPT", "CrossFit L2", "TRX Certified"],
    specialties: ["HIIT", "CrossFit", "Group Fitness"],
    image: "/images/trainers/trainer-2.jpg",
    instagram: "@sarahfitswill",
    classTypes: ["HIIT", "CrossFit"],
  },
  {
    id: "3",
    name: "David Rodriguez",
    slug: "david-rodriguez",
    specialty: "Boxing & MMA",
    experience: 15,
    bio: "Professional boxing coach with championship-level training methodology. David brings discipline and technique to every session.",
    longBio:
      "David grew up in a boxing family and started training at age 8. He went on to compete professionally, earning a regional championship title before retiring from competition. With 15 years of coaching experience, David has trained everyone from complete beginners to professional fighters. His approach emphasizes proper technique and footwork as the foundation for everything else. He believes boxing is the ultimate stress reliever and full-body workout, accessible to people of all fitness levels.",
    certifications: ["USA Boxing Coach", "NASM-CPT", "First Aid/CPR"],
    specialties: ["Boxing", "Kickboxing", "Self-Defense"],
    image: "/images/trainers/trainer-3.jpg",
    instagram: "@drodboxing",
    classTypes: ["Boxing"],
  },
  {
    id: "4",
    name: "Aisha Patel",
    slug: "aisha-patel",
    specialty: "Yoga & Mindfulness",
    experience: 10,
    bio: "Certified yoga therapist focused on the mind-body connection for holistic wellness. Aisha creates a space where everyone feels welcome.",
    longBio:
      "Aisha discovered yoga during a difficult period in her life and it became her anchor. She trained at an ashram in India, completing her 500-hour teacher training and additional certification in yoga therapy. Aisha's classes blend traditional yoga philosophy with modern sports science, making her sessions both spiritually grounding and physically challenging. She specializes in helping athletes improve flexibility and recovery, as well as guiding beginners through their first yoga experiences with patience and warmth.",
    certifications: ["RYT-500", "Yoga Therapy Cert", "Meditation Teacher"],
    specialties: ["Vinyasa", "Restorative Yoga", "Meditation"],
    image: "/images/trainers/trainer-4.jpg",
    instagram: "@aishaflowsyoga",
    classTypes: ["Yoga"],
  },
  {
    id: "5",
    name: "Jake Morrison",
    slug: "jake-morrison",
    specialty: "Sports Performance",
    experience: 9,
    bio: "Former collegiate athlete turned performance coach. Jake helps athletes of all levels reach their peak potential.",
    longBio:
      "Jake played Division I football before a knee injury redirected his path toward coaching. He earned his CSCS and specialized in sports performance, working with high school and college athletes for several years. His training programs are data-driven, using movement screens and performance metrics to create individualized progressions. Jake is also certified in corrective exercise, making him the go-to trainer for injury prevention and return-to-sport programs.",
    certifications: ["NSCA-CSCS", "NASM-CES", "FMS Level 2"],
    specialties: ["Sports Performance", "Injury Prevention", "Speed Training"],
    image: "/images/trainers/trainer-5.jpg",
    instagram: "@jakemperformance",
    classTypes: ["Strength", "CrossFit"],
  },
  {
    id: "6",
    name: "Nina Kowalski",
    slug: "nina-kowalski",
    specialty: "Dance Fitness & Cardio",
    experience: 6,
    bio: "Brings the party to every workout. Nina's dance-based fitness classes are the most fun you'll ever have while burning 600+ calories.",
    longBio:
      "Nina trained as a professional dancer for 10 years before channeling her passion into fitness. She created her own dance-based cardio format that blends hip-hop, Latin, and contemporary movement with high-intensity intervals. Her classes regularly sell out because they feel more like a night out than a workout. Nina believes that the best exercise is the one you actually enjoy doing, and she makes every class an unforgettable experience.",
    certifications: ["ACE-GFI", "Zumba Licensed", "Barre Certified"],
    specialties: ["Dance Fitness", "Barre", "Cardio"],
    image: "/images/trainers/trainer-6.jpg",
    instagram: "@ninakmoves",
    classTypes: ["HIIT"],
  },
] as const;
